l_english:
 POD_player_rage_growth_chance: "#TOOLTIP:POD_player_rage_growth_chance_tt #V;L [GetPlayer.MakeScope.ScriptValue('rage_growth_chance')|0]%#!#!"
 POD_player_rage_growth_chance_tt: "[GetPlayer.MakeScope.GetScriptValueDesc('rage_growth_chance')]"

 POD_rage_growth_base: "Base"
 POD_rage_growth_ragabash: "Your Auspice is [GetTrait('ragabash').GetName(GetPlayer)]"
 POD_rage_growth_theurge: "Your Auspice is [GetTrait('theurge').GetName(GetPlayer)]"
 POD_rage_growth_philodox: "Your Auspice is [GetTrait('philodox').GetName(GetPlayer)]"
 POD_rage_growth_galliard: "Your Auspice is [GetTrait('galliard').GetName(GetPlayer)]"
 POD_rage_growth_ahroun: "Your Auspice is [GetTrait('ahroun').GetName(GetPlayer)]"
 POD_rage_growth_wrathful: "You are [GetTrait('wrathful').GetName(GetPlayer)]"
 POD_rage_growth_irritable: "You are [GetTrait('irritable').GetName(GetPlayer)]"
 POD_rage_growth_calm: "You are [GetTrait('calm').GetName(GetPlayer)]"
 POD_rage_growth_wyld: "Your [faith|E] is #TOOLTIP:GAME_FAITH_DOCTRINE,doctrine_triat_alignment_wyld #L Wyld-aligned#!#!"
 POD_rage_growth_weaver: "Your [faith|E] is #TOOLTIP:GAME_FAITH_DOCTRINE,doctrine_triat_alignment_weaver #L Weaver-aligned#!#!"
 POD_rage_growth_blood_running_hot: "You have the [GetPerk('blood_running_hot_perk').GetName(GetPlayer)] [perk|E]"
 POD_rage_growth_berseker: "You have the [GetPerk('fomori_berseker_perk').GetName(GetPlayer)] [perk|E]"
 POD_rage_growth_stress: "You are extremely stressed"

 POD_player_gnosis_regen_chance: "#TOOLTIP:POD_player_gnosis_regen_chance_tt #V;L [GetPlayer.MakeScope.ScriptValue('gnosis_regen_chance')|0]%#!#!"
 POD_player_gnosis_regen_chance_tt: "[GetPlayer.MakeScope.GetScriptValueDesc('gnosis_regen_chance')]"

 POD_gnosis_regen_base: "Base"
 POD_gnosis_regen_homid_born: "Your Breed is [GetTrait('homid_born').GetName(GetPlayer)]"
 POD_gnosis_regen_metis: "Your Breed is [GetTrait('metis').GetName(GetPlayer)]"
 POD_gnosis_regen_beast_born: "Your Breed is [GetTrait('beast_born').GetName(GetPlayer)]"
 POD_gnosis_regen_piety_level_1: "Your [piety_level|E] is [GetModifier('piety_level_1').GetNameWithTooltip|L]"
 POD_gnosis_regen_piety_level_2: "Your [piety_level|E] is [GetModifier('piety_level_2').GetNameWithTooltip|L]"
 POD_gnosis_regen_piety_level_3: "Your [piety_level|E] is [GetModifier('piety_level_3').GetNameWithTooltip|L]"
 POD_gnosis_regen_piety_level_4: "Your [piety_level|E] is [GetModifier('piety_level_4').GetNameWithTooltip|L]"
 POD_gnosis_regen_piety_level_5: "Your [piety_level|E] is [GetModifier('piety_level_5').GetNameWithTooltip|L]"
 POD_gnosis_regen_kinfolk_gnosis: "You have [GetTrait('gnosis').GetName(GetPlayer)]"
 POD_gnosis_regen_spirit_ties: "You have the [GetPerk('fomori_spirit_ties_perk').GetName(GetPlayer)] [perk|E]"
 POD_artifact_helping_gnosis_chance: "You have an [artifact|E] improving your Gnosis regeneration chance"
 POD_gnosis_regen_stress: "You are extremely stressed"
 POD_gnosis_regen_kinfolk_cap: "[GetTrait('kinfolk').GetName(GetPlayer)] can't have more than #V 3#! Gnosis"

 POD_player_befriend_limit: "#TOOLTIP:POD_player_befriend_limit_tt #V;L [GetPlayer.MakeScope.ScriptValue('POD_befriend_limit')|0]#!#!"
 POD_player_befriend_limit_tt: "[GetPlayer.MakeScope.GetScriptValueDesc('POD_befriend_limit')]"
 POD_befriend_limit_setite: "[GetPlayer.GetDynasty.GetName] has #TOOLTIP:DYNASTY_PERK,setite_legacy_2 #L $setite_legacy_2_name$#!#!"
 POD_befriend_limit_seelie: "[GetPlayer.GetDynasty.GetName] has #TOOLTIP:DYNASTY_PERK,seelie_romantic_legacy_2 #L $seelie_romantic_legacy_2_name$#!#!"


 POD_FORMAT_BASE_POSITIVE: "$KEY$: #P $VALUE|0$#!"
 POD_FORMAT_POSITIVE: "$KEY$: #P +$VALUE|0$#!"
 POD_FORMAT_PERCENTAGE_BASE: "$KEY$: #P $VALUE|0$%#!"
 POD_FORMAT_PERCENTAGE_MODIFIER: "$KEY$: #P +$VALUE|0$%#!"
 POD_FORMAT_PERCENTAGE_MODIFIER_NEGATIVE: "$KEY$: #N $VALUE|0$%#!"
 POD_FORMAT_PERCENTAGE_DOUBLED: "$KEY$: #P +100%#!"
 POD_FORMAT_PERCENTAGE_NULLIFIED: "$KEY$: #N -100%#!"